/// CORE CONCEPTS THAT WILL BE USED

////// FRACTAL LOGIC W/ EXIT CONDITION(AL)S
////// ARRAYS/OBJECT PAIRINGS 
////////// CREATING/PUSHING NEW BRANCH OBJECT (SIMULTANEOUSLY TO ARRAY AND TO SKETCH) W/ EMBEDDED USER DATA FROM SERVER WHEN USER POSTS NEW RESPONSE
////// OBJECT-SPECIFIC LOGIC/INTERACTIONS 

//CAITY'S CODING PLAN STEPS

//Completed Steps 

//1. CREATE GLITCH PAGES -- LINK LIBRARIES/P5 CDNS, OTHER PAGES IN HTML
//2. ADD IN OBJECT-ORIENTED FRACTAL TREE CODE
//3. RESOLVE HOW TO USE P5JS/PREVEW SKETCHES IN APP.JS IN GLITCH AND/OR VS CODE
//4. ONCE FUNCTIONAL, WIREFRAME & SET UP BASIC LANDING PAGE/WEBPAGE LAYOUT 

//TODO

//5. DEFINE THE BRANCH OBJECT AND CONSTRUCTORS IN BRANCH.JS 

  //WE WILL BE PASSING/PUSHING USER DATA INTO THE BRANCH OBJECT ARRAY//POSTING//GETTING TO SERVER)
//6. FIGURE OUT IF THE P5 FRACTAL TREE SHOULD BE CODED IN SKETCH.JS OR APP.JS 
//6. ONCE CLARIFIED, START CODING THE FRACTAL LOGIC -- 

//////EASIEST VERSION IS TO START W/ THE ROOT=BRANCH[0] DRAWN WITH BRANCH[1] AND BRANCH[2] DRAWN,
/////////DATA CAN BE STORED IN EACH BRANCH TO HOVER AS A WAY OF BETTER EXPLAINING THE PREMISE WHEN
////////USER HOVERS OVER BRANCHES[0],[1],[2]. 

//////////////BRANCH[0]--WILL HAVE STORED TEXT ABOUT THE HELLO, WORLD TREE OF LIFE / 
///////////////AS ONE OF THE MOST UNIVERSAL HUMAN SYMBOLS, WHICH HOPEFULLY CAN SERVE AS A SYMBOL FOR THE ROOT FOR A VIBRANT FUTURE GLOBAL SOCIETY 
//////////////(IN THE REAL WORLD AND THE VIRTUAL) -- DESPITE FEELING SLIGHTLY JADED/DISENCHANTED, I STILL WANT THIS FOR HUMANITY, IF POSSIBLE 
//////////////BRANCH[1] -- LEFT BRANCH SIGNIFIES  "PAST", RIGHT BRANCH SIGNIFIES "FUTURE"
//////////////BRANCH[2] -- BRANCH 2.1: VISION & VALUES BRANCH 2.2. MYTHS/STORYTELLING 2.3. CULTURAL TRADITIONS 2.4. SKILLS, KNOWLEDGE, & WISDOM
//////////////BRANCH[3] -- WHERE USER ENTRIES BEGIN 

//7. CREATE USER INTERACTION DATA SUBMISSION TEXT BOX (SET UP FIRST, THEN LINK TO BACKEND WHEN BACKEND READY)
//8. CREATE / LINK MONGO DB/TERMINAL (POSSIBLY/PROBABLY ALL CODE WRITTEN TO VS CODE, IF NECESSARY)
//9. WRITE OUT CLIENT/SERVER DATA TRANSMISSION LOGIC FOR FETCH/POST // 

//////SENDING, STORING, RETRIEVING, DISPLAYING USER DATA FOR EACH RESPECTIVE NEW BRANCH OBJECT THAT IS PUSHED INTO THE ARRRAY WHEN USER POSTS IT & DISPLAYS RIGHT AWAY

//////////////////CLIENT-SIDE ACTIONS/FUNCTIONS #1: HOVER/CLICK ON DATA STORED IN BRANCH OBJECTS 
//////////////////CLIENT-SIDE ACTIONS/FUNCITONS #2: POST DATA TO THE SERVER & FETCH THE DATA TO SEE THE NEW BRANCH PUSHED/DISPLAYED 
//////////////////SERVER-SIDE ACTIONS/FUNCITONS: AUTOMAGICALLY POPULATES SOME DATA INTO THE BRANCH[0]=[2] OBJECTS FOR USERS TO EXPLORE/DISCOVER, STORES/SENDS NEW USER DATA AS IT'S POSTED

//10. IF ALL THIS IS DONE, THEN AESTHETICS CAN BE CONSIDERED -- COLORS, TEXTURES, 2D VS. 3D, VIBEY BACKGROUND MUSIC / SOUND FX TO GET YOU IN THE MOOD :) 
//11. IF THIS IS DONE, THEN A BASIC RESPONSE COUNTER COULD BE CREATED, BUT NEED NOT BE
//12. LIKEWISE IF ALL ELSE IS DONE, THERE ARE MANY VERY COOL APIS THAT WOULD BE VERY COOL TO LINK HERE -- GLOBAL CULTURAL TRADITIONS AND MYTHS, ETC. 

//UNESCO API: UNESCO (United Nations Educational, Scientific and Cultural Organization) 
//Smithsonian Institution Open Access API //GOOGLE KNOWLEDGE GRAPH API //Museum of the World API
//Global Forest Watch API: // NASA Earth Observing System Data and Information System (EOSDIS) API
